### ISSUE TITLE
Not able to get results on yql consulting finance API

### ISSUE THREAD

**Issue by mauricionr** [yql/yql-tables#477]
Yesterday this were working fine.

https://developer.yahoo.com/yql/

select \* from json where url="http://finance.yahoo.com/webservice/v1/symbols/TRPL4.SA,TRPL3.SA/quote?format=json" and itemPath = "list.resources.resource.fields"

![image](https://cloud.githubusercontent.com/assets/2263551/16884676/16e0404a-4aa1-11e6-9538-e41105fc4a5d.png)

Any ideia?

Thanks

**Comment by mauricionr** [comment]
Hi @davglass do you know anything about this or anyone who knows?

Thanks and sorry for bother you!

**Comment by devzero12** [comment]
Take a look at: https://github.com/yql/yql-tables/issues/476
